{
  "services": {
    "app_proxy": {
      "environment": {
        "APP_HOST": "paperclip-wallet_wallet_1",
        "APP_PORT": "3000"
      }
    },
    "wallet": {
      "image": "ghcr.io/connorslab/paperclip-wallet-app:beta-36859110457@sha256:c26b189eb5919781d362016c69b5a7a9606d042ee1117a7db366896aa18006a4",
      "user": "1000:1000",
      "restart": "unless-stopped",
      "stop_grace_period": "2m",
      "security_opt": [
        "no-new-privileges:true"
      ],
      "cap_drop": [
        "ALL"
      ],
      "volumes": [
        "${APP_DATA_DIR}/data:/data"
      ],
      "environment": {
        "APP_PASSWORD": "${APP_PASSWORD}",
        "PAPERCLIP_XBT_MAINNET": "1",
        "BARKD_UI_DEFAULT_ARK_SERVER": "https://ark.paperclippool.xyz"
      }
    }
  }
}
