{
  "services": {
    "app_proxy": {
      "environment": {
        "APP_HOST": "paperclip-wallet_wallet_1",
        "APP_PORT": "3000"
      }
    },
    "wallet": {
      "image": "ghcr.io/connorslab/paperclip-wallet-app:beta-bundled-37162659589@sha256:e8326633fa6fc933273ab0ddf1a18706d176382109a1be50248ce8b410b6a3e8",
      "user": "1000:1000",
      "restart": "unless-stopped",
      "stop_grace_period": "2m",
      "security_opt": [
        "no-new-privileges:true"
      ],
      "cap_drop": [
        "ALL"
      ],
      "volumes": [
        "${APP_DATA_DIR}/data:/data"
      ],
      "environment": {
        "APP_PASSWORD": "${APP_PASSWORD}",
        "PAPERCLIP_XBT_MAINNET": "1",
        "BARKD_UI_DEFAULT_ARK_SERVER": "https://ark.paperclippool.xyz"
      }
    }
  }
}
