{
  "services": {
    "app_proxy": {
      "environment": {
        "APP_HOST": "paperclip-wallet_wallet_1",
        "APP_PORT": "3000"
      }
    },
    "wallet": {
      "image": "ghcr.io/connorslab/paperclip-wallet-app:beta-36812151098@sha256:2213a045d0ff7b68eb0246089749d5db7e3d5591a53be788e60ac6aec837585e",
      "user": "1000:1000",
      "restart": "unless-stopped",
      "stop_grace_period": "2m",
      "security_opt": [
        "no-new-privileges:true"
      ],
      "cap_drop": [
        "ALL"
      ],
      "volumes": [
        "${APP_DATA_DIR}/data:/data"
      ],
      "environment": {
        "APP_PASSWORD": "${APP_PASSWORD}",
        "PAPERCLIP_XBT_MAINNET": "1",
        "BARKD_UI_DEFAULT_ARK_SERVER": "https://ark.paperclippool.xyz"
      }
    }
  }
}
